### Create a new note
POST http://localhost:3000/notes/create
Content-Type: application/json

{
    "title": "Kerja Kelompok",
    "datetime": "2024-12-04",
    "note": "Diskusi project massive."
}

### Get all notes
GET http://localhost:3000/notes

### Get a specific note by ID
GET http://localhost:3000/notes/1

### Update a note by ID
PUT http://localhost:3000/notes/update/1
Content-Type: application/json

{
    "title": "Updated Meeting Notes",
    "datetime": "2024-12-04",
    "note": "Diskusi project massive."
}

### Delete a note by ID
DELETE http://localhost:3000/notes/1
